version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.5.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}

      - run:
          name: Build application
          command: npm run build

      - run:
          name: Send build stats to Relative CI
          command: node_modules/.bin/relative-ci-agent --webpack-stats artifacts/webpack.json

      - store_artifacts:
          path: ./artifacts
          destination: artifacts
